### ISSUE TITLE
cordova-plugin-magnetometer

### ISSUE THREAD

**Issue by bimbojones** [sdesalas/cordova-magnetometer-app#1]
Tried to use the plugin on https://github.com/sdesalas/cordova-plugin-magnetometer which this app is based on. It loads, but there is no magnetometer feedback. Is this plugin still valid? I was trying with phonegap but fellback to cordova, still didn't work. On the browser, it kept logging that "exec proxy not found for MagnetoMeter"
Thanks

**Comment by sdesalas** [comment]
The plugin is still working. Its written for cordova though. Phonegap is just a fork so I imagine it works fine there too.

This app is a test harness: https://github.com/sdesalas/cordova-magnetometer-app

Obviously you cannot use it on the browser, since the browser has no magenetometer. It needs to be hooked up to a cordova webview.

**Comment by bimbojones** [comment]
I got it to work eventually, but thanks for the explanation.
